

const Terms = () => {
    return (
        <div>
            <div className="w-full h-full bg-white mt-28 ">
                <div className="w-4/5 mx-auto p-20 ">
                    <h1 className="text-sky-900 font-serif text-6xl">Privacy & Policy</h1>
                    <h4 className="text-sky-900 font-serif text-2xl mt-10">Centura Health Corporation</h4>
                    <h4 className="font-bold text-xl mt-2">Terms & conditions</h4>
                    <p className="text-lg mt-1">The Centura Health website (the “Site”) and Centura Health mobile application (“MyCenturaHealth” or the “App”) offer health care information and access to various services (collectively, the “Services”) provided by Centura Health Corporation, its affiliates or organizations, successors, assigns or licensees, together with any of their respective officers, directors and employees (“Centura Health”). Use of the Site or App and their Services is governed by the terms and conditions of this agreement (“Terms of Use” or “Agreement”). Throughout this Agreement, Centura Health is referred to as “we” or “us.” Individuals accessing the Site or App and the Services shall be referred to as “You” or “User(s)”. You agree that your use of the Site or App and any uses of Services are subject to your agreement with these Terms of Use. Your access and continued use of the Site or App indicates your consent to this Agreement. If You do not agree to the Terms of Use, You may not use the Site or App or the Services. Centura Health may modify these Terms of Use from time to time or at any time by posting updates to this page or any successor of this page. Your access and continued use of the Site or App after any such change indicates your consent to any such modified Terms of Use.</p>
                    <h4 className="font-bold text-xl mt-2">Your account profile, access & use of the site</h4>
                    <p className="text-lg mt-1">Prior to Your access to certain Services available on the Site or App (such as appointment scheduling or online payments), You will be required to create a personal profile account and reconfirm your acceptance of these Terms of Use. You are responsible for maintaining the confidentiality of all user identification, password and other confidential information relating to the use of your account and are fully responsible for all activities that occur under your account. You are responsible for taking all reasonable steps to ensure that no unauthorized person shall have access to your account. Payment transactions may be subject to additional terms of use.</p>
                    <h4 className="font-bold text-xl mt-2">Medical emergency disclaimer</h4>
                    <p className="text-lg mt-1">If You are experiencing a medical emergency, call emergency personnel (911) immediately and/or contact your local hospital right away. Do not rely on electronic communications through this Site or App for assistance for medical emergencies or urgent medical needs. Any information provided on this Site regarding emergency room wait times or availability is provided for informational purposes only, and Centura Health does not warrant the accuracy or timeliness of any such information.</p>
                    <h4 className="font-bold text-xl mt-2">Site services are not medical advice</h4>
                    <p className="text-lg mt-1">We advise Users to always seek the advice of a physician or other qualified health care provider with any questions regarding personal health or medical conditions. Never disregard, avoid or delay in obtaining medical advice from your doctor or other qualified health care provider because of something You have read on this Site or App. If You have or suspect that You have a medical problem or condition, please contact a qualified health care professional immediately. Nothing contained in the Site or App is or should be considered, or used as a substitute for, individual medical advice, diagnosis or treatment.</p>
                    <h4 className="font-bold text-xl mt-2">Medical records storage & electronic communications</h4>
                    <p className="text-lg mt-1">You may have the opportunity to access healthcare records and information through the Site or App (“Your Records”). You hereby grant Centura Health, our employees, officers, directors, agents, and contractors, and all other persons or entities involved in the operation of this Site or App, the right to access, transmit, receive, monitor, retrieve, store, maintain, and use Your Records in connection with the establishment and maintenance of your Centura Health account to provide the Services and operate the Site or App. You are also responsible for reviewing your account information as well as any documents produced by Centura Health. Some Services provide secure electronic communications services related to Your healthcare. Note that email transmissions cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, and Centura Health therefore does not accept liability for any errors or omissions in the contents or receipt of e-mail transmissions. You are responsible for utilizing provided secure electronic communication services provided in the Services in order to preserve security of Your Records.</p>
                    <h4 className="font-bold text-xl mt-2">Disclaimer, warranties & limitation of liability </h4>
                    <p className="text-lg mt-1">THE SERVICES AND ANY INFORMATION CONTAINED ON THE SITE OR APP OR PROVIDED THROUGH THE SERVICES ARE PROVIDED ON AN “AS IS” BASIS. WE WILL REGARD ALL ACCESS TO AND USE OF THIS SITE OR APP AS VOLUNTARY AND AT THE SOLE RISK OF THE USER. WE DO NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES, REPRESENTATIONS OR ENDORSEMENTS OF ANY KIND WHATSOEVER (INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE OR NON-INFRINGEMENT, OR ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE) WITH REGARD TO THE SERVICES, OR WITH RESPECT TO ANY INFORMATION, PRODUCT, SERVICE, MERCHANDISE OR OTHER MATERIAL PROVIDED ON OR THROUGH THE SITE. WE DO NOT WARRANT OR GUARANTEE THE ACCURACY, COMPLETENESS, CORRECTNESS, TIMELINESS OR USEFULNESS OF ANY INFORMATION, PRODUCTS, SERVICES, MERCHANDISE OR OTHER MATERIAL PROVIDED THROUGH THE SERVICES OR ON THE SITE GENERALLY. WE MAKE NO WARRANTY OR GUARANTEE THAT THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE.</p>
                    <h4 className="font-bold text-xl mt-2">Children's privacy </h4>
                    <p className="text-lg mt-1">We are committed to protecting the privacy of children. You should be aware that this Site and App are not intended or designed to attract children, or anyone under the age of 18. Parents and authorized legal guardians may utilize the Site or App and authorize use of the Site or App by minors as provided herein and in accordance with Centura Health policies.</p>
                    <h4 className="font-bold text-xl mt-2">Indemnity </h4>
                    <p className="text-lg mt-1">You agree that You are solely responsible for anything You post on the Site or App and that You will defend, indemnify, and hold Centura Health, its officers, directors, affiliates, employees, agents, licensors, and suppliers, harmless from and against any claims, actions or demands, liabilities and settlements including without limitation, reasonable legal and accounting fees, resulting from, or alleged to result from, your violation of these Terms of Use or any claims based upon your Postings on the Site or App or use of the Services.</p>
                    <h4 className="font-bold text-xl mt-2">Governing law & venue; territory; devices</h4>
                    <p className="text-lg mt-1">This Agreement is entered into between You and Centura Health in the State of Colorado, and is performed within the State of Colorado and governed by and shall be construed in all respects under the laws of the State of Colorado, exclusive of its choice of law or conflict of laws provisions. In any claim or action by You directly or indirectly arising under this Agreement or related to the Services, You irrevocably agree to submit to the exclusive personal jurisdiction of the state and federal courts located in Denver County, Colorado. You waive any jurisdictional, venue or inconvenient forum objections to such court. If any of the provisions of this Agreement are held to be unenforceable by a court or other tribunal of competent jurisdiction, then such provisions shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect. This Site and App are intended for use within the United States and its territories and protectorates (the “Territory”). You assume full responsibility for any use of this Site or App outside the Territory, which is at Your sole risk. Centura Health may provide this Site or App or Services on multiple platforms, operating systems, mobile devices, etc. Use of modified systems or devices may compromise the Site or App and/or Services, including necessary security services. Any use of the Site or App or Services on a rooted, jailbroken or otherwise adulterated device is expressly forbidden.</p>
                    <h4 className="font-bold text-xl mt-2">Rights, remedy & termination of services </h4>
                    <p className="text-lg mt-1">Centura Health may, in its sole discretion, terminate your access to the Services, or any portion thereof, or discontinue providing the Site or App, or any portion thereof. Centura Health may notify You that You have breached the Agreement and your account is being terminated. These actions are in addition to and not in lieu or limitation of any other right or remedy Centura Health may have available at law. Further, Centura Health shall not be liable to You or any third party for any such termination or discontinuance.</p>
                    <h4 className="font-bold text-xl mt-2">Limitation of liability </h4>
                    <p className="text-lg mt-1">TO THE EXTENT ALLOWED BY LAW, YOU EXPRESSLY UNDERSTAND AND AGREE THAT CENTURA HEALTH SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR INJURY, ILLNESS, DISABILITY, LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF CENTURA HEALTH HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICES; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICES; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SITE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICES. NOT WITHSTANDING THE FOREGOING, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF CENTURA HEALTH EXCEED THE TOTAL AMOUNT OF FEES PREVIOUSLY PAID BY YOU TO CENTURA HEALTH RELATING TO THE AFFECTED SERVICES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
                    <h4 className="font-bold text-xl mt-2">Proprietary rights </h4>
                    <p className="text-lg mt-1">The materials on the Site and App are copyrighted by Centura Health and/or other applicable rights holders. You acknowledge and agree that the Site and App and any necessary software used in connection with the Site and App (“Software”) contain proprietary and confidential information that is protected by applicable intellectual property and other laws. You further acknowledge and agree that any content contained in sponsor advertisements or information presented to You through the Site or App or advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by Centura Health or advertisers, You agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Site or App or the Software, in whole or in part. You may download and reprint a single copy of the materials from the Site or App and/or the Services for your own personal, noncommercial use only, provided You include all applicable notices and disclaimers. You agree not to modify the Software in any manner or form, or to use modified versions of the Software, including (without limitation) for the purpose of obtaining unauthorized access to the Site or App. You agree not to access the Site or App by any means other than through the interface that is provided by Centura Health for use in accessing the Site or App. You shall not, in whole or in part, adapt, translate, modify, decompile, reverse engineer, or disassemble the Site or App, merge the Site or App into other program material, nor shall You otherwise create or attempt to obtain the source code of the Software.</p>
                    <h4 className="font-bold text-xl mt-2">Use of location data </h4>
                    <p className="text-lg mt-1">If You have enabled the appointment arrival feature in the App, Centura Health may use Your precise geographical location information in order to identify when You arrive for Your appointment so that we can automatically check You in. You can disable this feature through the App at any time if you no longer wish to have your location disclosed. Centura Health does not collect precise geographical location information while you are accessing the Site.</p>
                    <h4 className="font-bold text-xl mt-2">Links to third-party sites </h4>
                    <p className="text-lg mt-1">The Site or App may contain links to sites maintained by third parties. Such links are provided for Your convenience and reference only. Centura Health does not operate or control in any respect any information, software, products or services available on such sites. Centura Health’s inclusion of a link to a site does not imply any endorsement of the services or the site, its contents, or its sponsoring organization. When You leave the Site or App please note that Centura Health is not responsible for the accuracy or content of the information provided by that site, nor is it liable for any direct or indirect technical or system issues arising out of Your access to or use of third party technologies or programs available through that site. Your use of a third party site linked from the Site or App is at Your own risk and will be governed by such third party’s terms and policies.</p>
                    <h4 className="font-bold text-xl mt-2">Complete agreement </h4>
                    <p className="text-lg mt-1">The Terms of Use, the Privacy Policy, and any Additional Terms of Use related to specific Services, and all associated and incorporated agreements (collectively the “Agreements”) which together set forth the relationship between You and Centura Health are intended to be read concurrently. The Agreements constitute the entire agreement between You and Centura Health with respect to the use of the Site or App and its Services.</p>
                </div>
            </div>
        </div>
    )
}


export default Terms;